In [7]:
import numpy as np

a = np.array([1, 1, 5, 5, 8, 8])

idx = np.cumsum(np.r_[0, a[1:] != a[:-1]])

print(idx)

[0 0 1 1 2 2]


In [4]:
np.diff(a)

array([0, 4, 0, 3, 0])

In [6]:
np.diff(a, prepend=a[0])

array([0, 0, 4, 0, 3, 0])

In [9]:
max(l for l in ())

ValueError: max() arg is an empty sequence